---
# tasks file for create_automation_account
- name: Add {{ automation_user }} user with hashed password
  user:
    name: {{ automation_user }}
    comment: "Create account used for Automation Tasks"
    password: "{{ automation_userpassword | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: on_create
- name: Add public ssh key for {{ automation_user }}
  authorized_key: 
    user: {{ automation_user }}
    state: present
    key: "{{ lookup('file', 'files/ssh/id_rsa.pub') }}"
- name: Add {{ automation_user }} user to sudoers with NOPASSWD
  lineinfile:
    dest: /etc/sudoers
    regexp: '^includedir '
    insertafter: '^#includedir '
    line: '{{ automation_user }}      ALL=(ALL)       NOPASSWD: ALL'
    validate: /sbin/visudo -cf %s



